language:
  - python
python:  
  - "3.7"
  - "3.8"
  - "nightly"
scripts:
  - python -m doctest counter.py
  - python -m doctest ucsd-ext-put-final/calculator.py
  - pytest
env: PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/tests:$TRAVIS_BUILD_DIR/ucsd-ext-put-final  
